name: MirrorChyan Uploading

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  mirrorchyan:
    runs-on: macos-latest
    strategy:
      matrix:
        os: [win, macos, linux]
        arch: [aarch64, x86_64]

    steps:
      - id: uploading
        uses: MirrorChyan/uploading-action@v1
        with:
          filetype: latest-release
          filename: "MAA-${{ matrix.os }}-${{ matrix.arch }}-*.zip"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: MaaXYZ
          repo: MaaFramework
          mirrorchyan_rid: MaaFramework
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
          os: ${{ matrix.os }}
          arch: ${{ matrix.arch }}
          auto_channel: true
